import { Alert, Incident, KPIData, ComplianceFramework, ThreatIntel } from './types';

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    title: 'Brute Force Attack Detected',
    severity: 'Critical',
    status: 'New',
    source: 'Firewall',
    timestamp: '2024-01-15T08:23:11Z',
    description: 'Multiple failed authentication attempts from external IP detected on SSH service.',
    mitre: ['T1110', 'T1021'],
    affectedHost: 'web-server-01',
    sourceIP: '185.220.101.45',
    tenantId: 'tenant-001',
    aiSummary: 'High-confidence brute force attack targeting SSH. Pattern matches known Mirai botnet behavior. Recommend immediate IP block and MFA enforcement.',
  },
  {
    id: 'ALT-002',
    title: 'Ransomware Behavior Detected',
    severity: 'Critical',
    status: 'Investigating',
    source: 'EDR',
    timestamp: '2024-01-15T07:45:00Z',
    description: 'File encryption activity detected on endpoint. Multiple files being renamed with unknown extensions.',
    mitre: ['T1486', 'T1083'],
    affectedHost: 'finance-ws-03',
    sourceIP: '10.0.5.23',
    assignee: 'analyst-01',
    tenantId: 'tenant-001',
    aiSummary: 'Ransomware behavior confirmed. File encryption rate of 200 files/min. Lateral movement indicators present. IMMEDIATE ISOLATION REQUIRED.',
  },
  {
    id: 'ALT-003',
    title: 'Data Exfiltration Attempt',
    severity: 'High',
    status: 'Acknowledged',
    source: 'DLP',
    timestamp: '2024-01-15T06:12:33Z',
    description: 'Large data transfer to external IP detected. 2.3GB transferred in 15 minutes.',
    mitre: ['T1048', 'T1567'],
    affectedHost: 'db-server-02',
    sourceIP: '10.0.2.45',
    tenantId: 'tenant-001',
    aiSummary: 'Potential data exfiltration via HTTPS. Destination IP maps to cloud storage in unrecognized country. Behavioral anomaly score: 94/100.',
  },
  {
    id: 'ALT-004',
    title: 'Privilege Escalation Attempt',
    severity: 'High',
    status: 'New',
    source: 'SIEM',
    timestamp: '2024-01-15T05:55:00Z',
    description: 'Suspicious use of sudo and setuid binaries detected.',
    mitre: ['T1548', 'T1055'],
    affectedHost: 'app-server-01',
    sourceIP: '10.0.1.15',
    tenantId: 'tenant-001',
    aiSummary: 'Privilege escalation via sudo abuse. Account compromised 2 hours prior. Attacker moving laterally.',
  },
  {
    id: 'ALT-005',
    title: 'Phishing Email Campaign',
    severity: 'High',
    status: 'Resolved',
    source: 'Email Gateway',
    timestamp: '2024-01-15T04:30:00Z',
    description: '47 malicious emails blocked targeting finance department.',
    mitre: ['T1566', 'T1598'],
    affectedHost: 'mail-server-01',
    sourceIP: '209.85.128.0',
    tenantId: 'tenant-001',
    aiSummary: 'Coordinated spear-phishing campaign targeting finance. Impersonating CFO. 3 links to credential harvesting sites.',
  },
  {
    id: 'ALT-006',
    title: 'SQL Injection Attack',
    severity: 'High',
    status: 'Investigating',
    source: 'WAF',
    timestamp: '2024-01-15T03:15:00Z',
    description: 'SQL injection patterns detected in web application requests.',
    mitre: ['T1190', 'T1505'],
    affectedHost: 'web-app-02',
    sourceIP: '45.33.32.156',
    tenantId: 'tenant-001',
    aiSummary: 'Advanced SQL injection using time-based blind technique. Targeting user credentials table. 89 requests in 2 minutes.',
  },
  {
    id: 'ALT-007',
    title: 'Lateral Movement Detected',
    severity: 'High',
    status: 'New',
    source: 'NDR',
    timestamp: '2024-01-15T02:00:00Z',
    description: 'Unusual internal traffic patterns suggest lateral movement.',
    mitre: ['T1021', 'T1570'],
    affectedHost: 'internal-switch-01',
    sourceIP: '10.0.3.67',
    tenantId: 'tenant-001',
    aiSummary: 'Lateral movement using SMB. Worm-like propagation pattern. 12 hosts scanned in last hour.',
  },
  {
    id: 'ALT-008',
    title: 'Suspicious PowerShell Execution',
    severity: 'Medium',
    status: 'Acknowledged',
    source: 'EDR',
    timestamp: '2024-01-15T01:45:00Z',
    description: 'Obfuscated PowerShell command executed by non-admin user.',
    mitre: ['T1059.001', 'T1027'],
    affectedHost: 'desktop-045',
    sourceIP: '10.0.10.45',
    tenantId: 'tenant-001',
    aiSummary: 'Base64-encoded PowerShell payload. Downloads secondary stage from external URL. Low persistence mechanism installed.',
  },
  {
    id: 'ALT-009',
    title: 'Unauthorized Cloud API Access',
    severity: 'Medium',
    status: 'New',
    source: 'Cloud SIEM',
    timestamp: '2024-01-14T23:30:00Z',
    description: 'API calls made from unrecognized geographic location.',
    mitre: ['T1078', 'T1530'],
    affectedHost: 'aws-s3-prod',
    sourceIP: '103.224.182.0',
    tenantId: 'tenant-001',
    aiSummary: 'AWS API access from Vietnam. User account normally accesses from UK. Possible credential theft.',
  },
  {
    id: 'ALT-010',
    title: 'Certificate Anomaly',
    severity: 'Medium',
    status: 'Closed',
    source: 'PKI Monitor',
    timestamp: '2024-01-14T22:00:00Z',
    description: 'Self-signed certificate used on internal service.',
    mitre: ['T1553', 'T1557'],
    affectedHost: 'internal-api-01',
    sourceIP: '10.0.4.100',
    tenantId: 'tenant-001',
    aiSummary: 'Unexpected certificate change. Could indicate MITM setup. Previous cert was valid CA-signed.',
  },
  {
    id: 'ALT-011',
    title: 'Failed MFA Bypass Attempt',
    severity: 'Medium',
    status: 'Resolved',
    source: 'IAM',
    timestamp: '2024-01-14T21:15:00Z',
    description: 'Multiple MFA bypass attempts on VPN access.',
    mitre: ['T1621', 'T1078'],
    affectedHost: 'vpn-gateway-01',
    sourceIP: '91.108.4.0',
    tenantId: 'tenant-001',
    aiSummary: 'MFA fatigue attack. 23 push notifications sent to target user. Account temporarily locked.',
  },
  {
    id: 'ALT-012',
    title: 'DNS Tunneling Activity',
    severity: 'Medium',
    status: 'Investigating',
    source: 'DNS Monitor',
    timestamp: '2024-01-14T20:00:00Z',
    description: 'Anomalous DNS query patterns suggesting data tunneling.',
    mitre: ['T1071.004', 'T1048'],
    affectedHost: 'dns-server-01',
    sourceIP: '10.0.1.200',
    tenantId: 'tenant-001',
    aiSummary: 'DNS tunneling using TXT records. 500KB exfiltrated. Destination domain registered 3 days ago.',
  },
  {
    id: 'ALT-013',
    title: 'Port Scan Detected',
    severity: 'Low',
    status: 'Closed',
    source: 'Firewall',
    timestamp: '2024-01-14T18:30:00Z',
    description: 'Sequential port scan from external IP.',
    mitre: ['T1595', 'T1046'],
    affectedHost: 'perimeter-fw-01',
    sourceIP: '198.20.69.0',
    tenantId: 'tenant-001',
    aiSummary: 'Automated port scan. All common ports scanned. Likely reconnaissance. IP belongs to known scanning service.',
  },
  {
    id: 'ALT-014',
    title: 'Outdated SSL/TLS Version',
    severity: 'Low',
    status: 'Acknowledged',
    source: 'Vulnerability Scanner',
    timestamp: '2024-01-14T16:00:00Z',
    description: 'TLS 1.0 still enabled on legacy service.',
    mitre: ['T1040'],
    affectedHost: 'legacy-service-01',
    sourceIP: '10.0.8.50',
    tenantId: 'tenant-001',
    aiSummary: 'TLS 1.0 vulnerability. Susceptible to POODLE attack. Needs immediate patching.',
  },
  {
    id: 'ALT-015',
    title: 'Weak Password Policy Violation',
    severity: 'Low',
    status: 'Resolved',
    source: 'IAM',
    timestamp: '2024-01-14T14:00:00Z',
    description: 'User account with password not meeting complexity requirements.',
    mitre: ['T1110'],
    affectedHost: 'dc-01',
    sourceIP: '10.0.0.5',
    tenantId: 'tenant-001',
    aiSummary: 'Password policy violation detected. User notified and password reset forced.',
  },
  {
    id: 'ALT-016',
    title: 'Insider Threat Indicator',
    severity: 'Critical',
    status: 'New',
    source: 'UEBA',
    timestamp: '2024-01-15T09:00:00Z',
    description: 'Employee accessing sensitive data outside business hours with bulk download.',
    mitre: ['T1078', 'T1213'],
    affectedHost: 'file-server-01',
    sourceIP: '10.0.6.78',
    assignee: 'analyst-02',
    tenantId: 'tenant-001',
    aiSummary: 'Behavioral anomaly: 3AM access, 400+ files downloaded. Employee on notice period. Insider threat probability: 91%.',
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'INC-001',
    title: 'Active Ransomware Outbreak',
    severity: 'Critical',
    status: 'Active',
    alertIds: ['ALT-002', 'ALT-007'],
    tenantId: 'tenant-001',
    createdAt: '2024-01-15T08:00:00Z',
    playbookSteps: [
      {
        id: 'step-1',
        name: 'Isolate Affected Systems',
        status: 'completed',
        description: 'Quarantine all affected endpoints from the network',
        actions: ['Block network access for finance-ws-03', 'Disable user accounts', 'Snapshot VM state'],
      },
      {
        id: 'step-2',
        name: 'Collect Forensic Evidence',
        status: 'completed',
        description: 'Gather logs and memory dumps for analysis',
        actions: ['Capture memory dump', 'Collect event logs', 'Preserve disk image'],
      },
      {
        id: 'step-3',
        name: 'Identify Patient Zero',
        status: 'running',
        description: 'Trace back to initial infection vector',
        actions: ['Analyze email logs', 'Review web proxy logs', 'Check USB activity'],
      },
      {
        id: 'step-4',
        name: 'Contain Lateral Spread',
        status: 'pending',
        description: 'Prevent further propagation across network',
        actions: ['Update firewall rules', 'Block C2 IPs', 'Reset service accounts'],
      },
      {
        id: 'step-5',
        name: 'Eradicate Threat',
        status: 'pending',
        description: 'Remove all malicious artifacts',
        actions: ['Run AV scan', 'Remove persistence mechanisms', 'Patch vulnerabilities'],
      },
      {
        id: 'step-6',
        name: 'Recovery & Restore',
        status: 'pending',
        description: 'Restore systems from clean backups',
        actions: ['Restore from backup', 'Verify data integrity', 'Re-enable systems'],
      },
    ],
  },
  {
    id: 'INC-002',
    title: 'Data Exfiltration Campaign',
    severity: 'High',
    status: 'Investigating',
    alertIds: ['ALT-003', 'ALT-012'],
    tenantId: 'tenant-001',
    createdAt: '2024-01-15T06:30:00Z',
    playbookSteps: [
      {
        id: 'step-1',
        name: 'Block Exfiltration Channel',
        status: 'completed',
        description: 'Immediately block identified exfiltration paths',
        actions: ['Block destination IPs', 'Disable compromised credentials', 'Enable enhanced DLP'],
      },
      {
        id: 'step-2',
        name: 'Assess Data Impact',
        status: 'running',
        description: 'Determine what data was accessed or stolen',
        actions: ['Review DLP logs', 'Identify data classification', 'Calculate data volume'],
      },
      {
        id: 'step-3',
        name: 'Notify Stakeholders',
        status: 'pending',
        description: 'Inform legal, compliance, and management',
        actions: ['Brief CISO', 'Engage legal team', 'Assess regulatory notification requirements'],
      },
      {
        id: 'step-4',
        name: 'Root Cause Analysis',
        status: 'pending',
        description: 'Investigate how exfiltration occurred',
        actions: ['Trace access path', 'Review authentication logs', 'Analyze network flows'],
      },
    ],
  },
  {
    id: 'INC-003',
    title: 'Insider Threat Investigation',
    severity: 'Critical',
    status: 'Active',
    alertIds: ['ALT-016'],
    tenantId: 'tenant-001',
    createdAt: '2024-01-15T09:15:00Z',
    playbookSteps: [
      {
        id: 'step-1',
        name: 'Suspend User Access',
        status: 'completed',
        description: 'Immediately restrict the suspect user account',
        actions: ['Disable AD account', 'Revoke VPN access', 'Revoke cloud access'],
      },
      {
        id: 'step-2',
        name: 'Legal Hold',
        status: 'running',
        description: 'Preserve all evidence for potential legal proceedings',
        actions: ['Enable mailbox hold', 'Preserve file access logs', 'Document chain of custody'],
      },
      {
        id: 'step-3',
        name: 'HR Coordination',
        status: 'pending',
        description: 'Coordinate with HR and legal departments',
        actions: ['Brief HR manager', 'Engage employment lawyer', 'Prepare investigation report'],
      },
    ],
  },
];

export const mockKPIData: KPIData = {
  totalAlerts: 16,
  activeIncidents: 3,
  complianceScore: 87,
  activeAgents: 234,
  globalThreatScore: 73,
};

export const mockComplianceFrameworks: ComplianceFramework[] = [
  { name: 'SOC 2 Type II', coverage: 94, controls: 64, passed: 60, risk: 'Low' },
  { name: 'ISO 27001', coverage: 89, controls: 114, passed: 101, risk: 'Low' },
  { name: 'NIST CSF', coverage: 82, controls: 108, passed: 89, risk: 'Medium' },
  { name: 'PCI DSS v4', coverage: 76, controls: 300, passed: 228, risk: 'Medium' },
  { name: 'GDPR', coverage: 91, controls: 99, passed: 90, risk: 'Low' },
  { name: 'Basel III', coverage: 71, controls: 85, passed: 60, risk: 'High' },
  { name: 'IFRS 9', coverage: 65, controls: 42, passed: 27, risk: 'High' },
  { name: 'ESG Framework', coverage: 78, controls: 56, passed: 44, risk: 'Medium' },
];

export const mockThreatIntel: ThreatIntel[] = [
  { id: 'TI-001', type: 'IP', indicator: '185.220.101.45', confidence: 95, severity: 'Critical', source: 'AbuseIPDB', lastSeen: '2024-01-15T08:00:00Z', tags: ['brute-force', 'tor-exit'] },
  { id: 'TI-002', type: 'Domain', indicator: 'malware-c2-server.net', confidence: 98, severity: 'Critical', source: 'VirusTotal', lastSeen: '2024-01-15T07:30:00Z', tags: ['c2', 'ransomware'] },
  { id: 'TI-003', type: 'Hash', indicator: 'a1b2c3d4e5f67890abcdef1234567890', confidence: 88, severity: 'High', source: 'Mandiant', lastSeen: '2024-01-14T20:00:00Z', tags: ['trojan', 'stealer'] },
  { id: 'TI-004', type: 'IP', indicator: '45.33.32.156', confidence: 72, severity: 'High', source: 'Shodan', lastSeen: '2024-01-14T16:00:00Z', tags: ['scanner', 'sql-injection'] },
  { id: 'TI-005', type: 'URL', indicator: 'http://phish-creds.tk/login', confidence: 99, severity: 'Critical', source: 'PhishTank', lastSeen: '2024-01-15T06:00:00Z', tags: ['phishing', 'credential-harvest'] },
];

export const mockAlertTrendData = [
  { date: 'Jan 8', Critical: 3, High: 8, Medium: 12, Low: 20 },
  { date: 'Jan 9', Critical: 5, High: 10, Medium: 15, Low: 18 },
  { date: 'Jan 10', Critical: 2, High: 7, Medium: 11, Low: 22 },
  { date: 'Jan 11', Critical: 8, High: 14, Medium: 18, Low: 15 },
  { date: 'Jan 12', Critical: 4, High: 9, Medium: 13, Low: 19 },
  { date: 'Jan 13', Critical: 6, High: 11, Medium: 16, Low: 17 },
  { date: 'Jan 14', Critical: 7, High: 12, Medium: 14, Low: 21 },
  { date: 'Jan 15', Critical: 5, High: 8, Medium: 10, Low: 16 },
];

export const mockResponseTimeData = [
  { name: 'Critical', avgMinutes: 12 },
  { name: 'High', avgMinutes: 45 },
  { name: 'Medium', avgMinutes: 180 },
  { name: 'Low', avgMinutes: 720 },
];

export const mockSeverityDistribution = [
  { name: 'Critical', value: 3, color: '#ef4444' },
  { name: 'High', value: 6, color: '#f97316' },
  { name: 'Medium', value: 5, color: '#eab308' },
  { name: 'Low', value: 4, color: '#22c55e' },
];

export const mockGeoThreatData = [
  { country: 'Russia', threats: 45, lat: 61.524, lon: 105.3188 },
  { country: 'China', threats: 38, lat: 35.8617, lon: 104.1954 },
  { country: 'North Korea', threats: 22, lat: 40.3399, lon: 127.5101 },
  { country: 'Iran', threats: 19, lat: 32.4279, lon: 53.688 },
  { country: 'Brazil', threats: 12, lat: -14.235, lon: -51.9253 },
];
